

services:
  # 1. Baza Danych Postgres
  postgres:
    image: postgres:15
    container_name: my_project_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data # Zachowanie danych po restarcie

  # 2. Backend (NestJS)
  backend:
    build: ./backend
    container_name: my_project_backend
    expose:
      - "3000"
    environment:
      # host to nazwa serwisu 'postgres', a nie 'localhost'
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    depends_on:
      - postgres
    volumes:
      - ./backend:/app          
      - /app/node_modules         
    
    command: npm run start:dev

  # 3. Frontend (Vue)
  frontend:
    build: 
      context: ./frontend
      target: build-stage
    container_name: my_project_frontend
    expose:
      - "5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  nginx:
    image: nginx:alpine
    container_name: my_project_gateway
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  pg_data: